name: 镜像仓库到 Gitee
on:
  push:
    branches:
      - main
env:
  # 仓库名称
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  mirror-to-gitee:
    name: 同步到 Gitee
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repo to Gitee.
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: alinesno-cloud/${{ env.REPO_NAME }}
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}
