name: Sync To Gitee  #名字  可自定义
on: page_build  #触发条件   page_build表示Github Page部署完成后触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master #开源actions包
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:alinesno-infrastructure/alinesno-infra-platform-press.git" # github仓库地址
          destination-repo: "git@gitee.com:alinesno-cloud/alinesno-infra-platform-press.git" # gitee仓库地址
