on:
  push:
  pull_request_target:
    branches: [main]
name: Tests / test-org-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps: 
    - name: Organization mirror
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/alinesno-infrastructure
        dst: gitee/alinesno-cloud
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
        force_update: true
        debug: true


         
