on:
  push:
  pull_request_target:
    branches: [main]
name: Tests / test-org-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: ./.
      with:
        src: github/alinesno-infrastructure
        dst: gitee/alinesno-cloud
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
        
        # Only sync normal repo 
        force_update: true
        debug: true
         
