name: Gitee repos mirror periodic job
on: page_build  #触发条件   page_build表示Github Page部署完成后触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.01
      with:
        src: github/alinesno-infrastructure
        dst: gitee/alinesno-cloud
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: org
        timeout: 600
        debug: true
        force_update: true
